name: BetterUp - Build Docker Images and push to ECR
on:
  push:


jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: SUB_BUILD=PLATFORM ./gradlew buildDockerImage

      - name: Configure AWS User credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.GOV_DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GOV_DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Image Tag Env
        run: echo "TAG=$(date '+%Y.%-m.%-d').${GITHUB_SHA:0:4}" >> "$GITHUB_ENV"

      - name: List and Tag images
        run: |
          docker images|grep airbyte/|grep dev|awk '{print $1}'|sort > images.txt && \
          ./tools/bin/bu_tag_push.sh images.txt
